version: 0.2
env:
  parameter-store:
    ARTIFACTORY_API_KEY: "ARTIFACTORY_CREDENTIALS"
phases:
pre_build:
    commands:
      - echo Entering pre_build phase...
      - ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_API_KEY
      - sed -i -e 's|ARTIFACTORY_USER|${ARTIFACTORY_USER}|g' settings.xml && sed -i -e 's|ARTIFACTORY_PASSWORD|${ARTIFACTORY_API_KEY}|g' settings.xml && sed -i -e 's|ARTIFACTORY_MVN_REPO|${ARTIFACTORY_MVN_REPO}|g' settings.xml
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn -s settings.xml -f pom.xml compile
      - mvn -s settings.xml -f pom.xml package
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`i
      - ./jfrog rt u "*.war" libs-release-local --build-name=my-app --build-number=$CODEBUILD_BUILD_ID --flat=false
      - ./jfrog rt bce codestar-demo-java-app $CODEBUILD_BUILD_ID
      - ./jfrog rt bp codestar-demo-java-app $CODEBUILD_BUILD_ID
artifacts:
  files:
    - target/my-app-1.0-SNAPSHOT.jar
