# This is a basic workflow that is manually triggered

name: Pre PR checks
run-name: ${{github.actor}} os working on this

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  cla-message:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: getuser
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://punkers.pythonanywhere.com/check_user?user_id=user1'
          method: 'GET'
        if: steps.getuser.outputs.status != 200 
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            **If you haven't signed the [CLA] you need to do that before making any code changes. Check the README.md file.**
